name: Jira Test
on:
  push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      secret_thingy: ${{ secrets.JIRA_BASE_URL }}
    steps:
      - if: ${{ env.secret_thingy != '' }}
        run: echo 'The thingy has a value of ' ${{env.secret_thingy}}
      - if: ${{ env.secret_thingy == '' }}
        run: echo 'The thingy has no value!!!'
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_BASE_URL:  ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    - name: Jira TODO
      uses: atlassian/gajira-todo@master
      with:
        project: AT
        issuetype: Task
        description: Created automatically via Github Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

