name: Jira Test
on:
  push

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    env:
      secret_thingy: ${{ secrets.JIRA_BASE_URL }}
    steps:
      - if: ${{ env.secret_thingy != '' }}
        run: echo 'The thingy has a value of ' ${{env.secret_thingy}}
      - if: ${{ env.secret_thingy == '' }}
        run: echo 'The thingy has no value!'
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_BASE_URL:  ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

    - name: Find Commit Issue Key
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits
      id: commit_key

    - name: Find Branch Issue Key
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: branch
      id: branch_key

    - name: Output 1
      run: echo 'Issue Output2 - ' ${{ join(steps.commit_key.outputs.*, '\n') }}
    - name: Output 2
      run: echo 'Issue Output - ' ${{ join(steps.branch_key.outputs.*, '\n') }}

    - name: Jira Commit Issue Transition
      uses: atlassian/gajira-transition@v2.0.2
      with:
        # Key of the issue to be transitioned
        issue: ${{ join(steps.commit_key.outputs.*, '\n') }}
        # The transition to apply to the issue, e.g. 'In Progress'
        transition: 'In Progress'
        # The id of a transition to apply to the issue
        transitionId: # optional

    - name: Jira Branch Issue Transition
      uses: atlassian/gajira-transition@v2.0.2
      with:
        # Key of the issue to be transitioned
        issue: ${{ join(steps.branch_key.outputs.*, '\n') }}
        # The transition to apply to the issue, e.g. 'In Progress'
        transition: 'In Progress'
        # The id of a transition to apply to the issue
        transitionId: # optional

